- app.js
- bin/www
- package-lock.json
- package.json
- public/stylesheets/style.css
- routes/index.js
- routes/users.js
- views/error.ejs
- views/index.ejs
- `express-generator` 로 디렉토리 생성
> :sparkles: feat : 개발 환경 구축 #7

- public/stylesheets/style_desktop.css
- views/index.ejs
- views/layouts/desktopLayout.ejs
> :recycle: refactor : ejs 템플릿에서 defineContent 제거 #16

- controllers/consoleLogger.js
- controllers/initializePassport.js
- models/insertNewUser.js
- package-lock.json
- package.json
node-color-log를 써서 log가 이쁘게 나오게 했습니다..만 만족스럽지 않네요
모듈 의존성을 package.json에 추가했고, 기존 console.log, console.error를 바꿔줬습니다.
또한 로그에 남는 타임스템프가 한국과 다른 시간대여서, 한국 시간으로 보정해줬습니다.
```javascript
import consoleLogger from './controller/consoleLogger.js'
consoleLogger.info()
consoleLogger.error()
consoleLogger.debug()
consoleLogger.warn()
```
위와 같은 메소드들을 사용할 수 있습니다.
>  ✨ node-color-log를 활용하여 log가독성 개선 

- app.js
- controllers/insertEventController.js
- models/insertEvent.js
- package-lock.json
- package.json
- public/javascripts/eventForm/eventFormDisplay.js
- public/javascripts/userDropDown.js
- public/stylesheets/components/event_form.css
- public/stylesheets/components/header.css
- public/stylesheets/components/login.css
- public/stylesheets/components/main.css
- public/stylesheets/presets/color.css
- public/stylesheets/presets/layout_desktop.css
- public/stylesheets/style_desktop.css
- routes/event.js
- routes/index.js
- views/components/eventForm.ejs
- views/index.ejs
- views/layouts/desktopLayout.ejs
- views/login.ejs
- header 우측 user 드롭다운 버튼
- 내가 생성한 이벤트, 로그아웃 링크
> ✨ feat : user 드롭다운 버튼 #46

- public/javascripts/nav/nav.js
- public/stylesheets/components/nav.css
- public/stylesheets/presets/color.css
- views/layouts/desktopLayout.ejs
네비바를 만들었습니다
- 네비바를 만들었습니다.
- 카테고리 색깔을 변경하였습니다.
- 뷰포트 1080px 이하에선 햄버거 아이콘으로 넣을 예정입니다. 
- 애니메이션도 적절히 넣었습니다.
- 개선점이 보이면 피드백 부탁드립니다.
애니메이션
https://user-images.githubusercontent.com/79127797/150904624-f401eacd-d0d1-47e6-a178-df3269fa7684.mov
> 💄 style : 네비바 생성

- controllers/eventListController.js
- public/javascripts/eventList/addClickListenerForEdit.js
- public/javascripts/eventList/generateEventList.js
- public/javascripts/eventList/setLayoutForEventList.js
- public/stylesheets/components/contents/event_list.css
- public/stylesheets/components/nav.css
사소하지만 치명적인 버그들을 고쳤습니다.
- 내가 생성한 이벤트에 가지 못하는 현상을 고쳤습니다.
- 이벤트 편집 실패시 모달창이 너무 빨리 사라지는 버그를 고쳤습니다.
- 내가 생성한 이벤트 페이지에서 유저 정보를 select에 실패했을 때 서버가
터지는 문제를 고쳤습니다.
- 데스크톱 화면에서 모바일 화면의 토글 내부가 보이는 문제를 수정하였습니다.
생성한 이벤트가 없어도 내가 생성한 이벤트 페이지에 갈 수 있습니다.
이벤트가 없으면 헤더랑 푸터만 있는 페이지가 뜨는데, 어떤 메시지를 띄워줄진 차차 생각해보겠습니다..
> :bug: fix : 내가 만든 이벤트가 없을 때 홈으로 가는 버그 수정  #116

- lib/jwtUtils.js
- middlewares/verifyUser.js
첫 로그인 시 혹은 로그아웃시 에러 메시지가 출력되던 문제를 고쳤습니다.
- verify 하기 전 조건을 추가해줬습니다.
- res.locals.userId 를 넣는 시점이 이상했어서... 바르게 잡아줬습니다.
> 🐛  첫 로그인시 에러 메시지가 출력되던 버그 수정 

- public/stylesheets/components/login.css
- public/stylesheets/presets/layout_desktop.css
- 로그인 화면을 모바일화 하였습니다.
- 기본적인 레이아웃이 고정값으로 잡혀있어서 반응형으로 바꿨습니다.
- 미디어쿼리 호출을 최소화 하기 위하여 login.css에 미디어쿼리를 넣었습니다.
- 기존 UI와 흡사하지만 화면이 작아져도 스크롤이 생기지 않습니다.
> 💄  로그인 ui 모바일화 

- public/javascripts/calendar/month/fillDateEvents.js
- public/stylesheets/components/popups/event_details.css
- 이벤트 상세정보 팝업 x 위치 보정 
- 띠지 user-select: none 적용
> :lipstick: style : 이벤트 상세정보 팝업 x 위치 보정 & 띠지 user-select: none 적용

- public/javascripts/config/setGoogleAnalytics.js
- views/layouts/layout.ejs
- views/login.ejs
- GA 연결을 위한 gtag.js 코드 추가
- 모든 페이지에 적용시키기 위해 login.ejs, layouts/layout.ejs 두 곳에 모두 추가했습니다.
- 에러발생부분은 jiskim님이 eventInfo.js에서 수정을 통해 해결해주셨습니다. 
- 초기 설정과정 및 에러 부분들은 [노션](https://www.notion.so/78956cfb672c416a9d3035eddc4330b9) 간단하게 정리했습니다.
> :sparkles: feat : 구글 애널리틱스 적용

- README.md
> :memo: docs : README.md draft

- README.md
- controllers/eventController.js
- controllers/pushController.js
- lib/push/pushUtils.js
- lib/push/triggerPush.js
- models/accessMyEventTable.js
- models/accessPushSubscriptionTable.js
- public/javascripts/notification/initNotificationSetting.js
- #182 해결했습니다.
- 추가적으로 이벤트가 수정되면 해당 이벤트에 등록한 모든 사용자의 해당 event my_event 테이블의 sendAt column 업데이트 되는 문제 고쳤습니다.
- README.md 뱃지 alt 수정했습니다.
close #182
> :bug: fix : 사용자가 알림 설정 꺼도 알림 정보 my_event 테이블에 유지되는 현상 #182

- README.md
> :memo: docs : README.md 웹팩 배지 추가

- src/javascripts/eventForm/clickNewEventButton.js
- src/javascripts/eventPromotion/clickExitPromotion.js
- 이벤트 생성 후 홍보글 확인했을 때 바로 캘린더에 반영되도록 새로고침
> :sparkles: refactor : 이벤트 생성 후 홍보글 확인했을 때 바로 캘린더에 반영되도록 새로고침

- src/javascripts/eventDetail/utils/replaceToHyperlink.js
- anchor attribute `target='_blank'` 로 상세정보 링크 눌렀을 때 새탭에서 표시
> :sparkles: feat : 상세정보 링크 눌렀을 때 새탭에서 표시

- README.md
> :memo: docs : README.md 에 사용 가이드 링크 추가

- README.md
> :memo: docs : README.md 업데이트

- public/stylesheets/presets/layout.css
- public/stylesheets/presets/mobile_spec.css
- src/javascripts/eventDetail/clickMyEventOrCancelButton.js
- 인트라 구독과 혼란이 생겨서 구분하기 위한 경고 메시지를 추가하였습니다.
close #196
> 💄 모달창에 경고 메시지 추가

- package-lock.json
- src/javascripts/calendar/month/mapLabelSlots.js
- src/javascripts/header/hoverTodayButton.js
- 일요일에 끝나는 연일 이벤트 띠지가 첫번째 slot 에 위치하지 않을 때 생기는 띠지 배치 오류 수정했습니다. #199 
- github 에 security alert 뜨던 dependency 업데이트 했습니다.
- today 아이콘에 hover 했을 때 뜨는 팝업 길이가 조금 짧아 날짜가 가운데 정렬이 안 되고 있던 것 수정했습니다.
close #199
> 🐛 연일 이벤트 띠지 배치 오류 fix

- package-lock.json
- src/javascripts/calendar/month/mapLabelSlots.js
- src/javascripts/header/hoverTodayButton.js
- 일요일에 끝나는 연일 이벤트 띠지가 첫번째 slot 에 위치하지 않을 때 생기는 띠지 배치 오류 수정했습니다. #199
- github 에 security alert 뜨던 dependency 업데이트 했습니다.
- today 아이콘에 hover 했을 때 뜨는 팝업 길이가 조금 짧아 날짜가 가운데 정렬이 안 되고 있던 것 수정했습니다.
> 🐛 연일 이벤트 띠지 배치 오류 fix (merge into develop)

- README.md
- 리드미에 사이트 링크 추가
- 라이트모드 이슈 대응
> :memo: docs : README 업데이트

- controllers/initializePassport.js
- lib/jwtUtils.js
- 42 passport 에서 제공하는 profile 객체에서 프로필 이미지 주소 위치가 기존에는 profile.photo[0] 이 었는데 profile._json.image.link 로 변경되어서 db 에 JS undefined 값을 넣는 문제 해결
> 🐛 fix : profile image 주소 위치 변경
